### ISSUE TITLE
Block store: S3 uploads doesn’t scale linearly with number of tenants

### ISSUE THREAD

**Issue by harry671003** [cortexproject/cortex#2757]
## Issue

Cortex, with block store backend, distributes one tenant’s time-series across all ingesters. With the current architecture, the number of S3 uploads doesn’t scale linearly with number of tenants. Right now, it is not cost efficient to deploy large cortex clusters with block store backend due to high S3 costs.

This would be more evident if we look at two Cortex clusters consisting of different number of tenants as shown below. 

To simplify our calculations, let’s assume the following:
* All tenants have 100K time-series each.
* An ingester can hold a maximum of 1 million time-series.
* Cortex replication factor is 3.

### Cluster with 100 tenants

In a cluster with 100 tenants, we’ll have about RF x 100 x 100K = 30 million time series. It will requires about 30 ingesters to store time series from 100 tenants in a cluster. Given that time series from a tenant are distributed uniformly across all ingesters, every ingester would end up with one TSDB for every tenant.

Total number of uploads per TSDB block range period would be:
* Number of ingesters x Number of tenants
* 30 * 100 = **3,000 uploads** (assuming only one upload per TSDB).

### Cluster with 1000 tenants

Total number of time-series in this case would be 300 million and this requires 300 ingesters.

Total number of uploads per TSDB block range period would be:
* Number of ingesters x Number of tenants
* 300 * 1000 = **300,000 uploads** (assuming only one upload per TSDB).

Here, the issue is that S3 uploads is growing at a rate proportional to tenant ^ 2. This also affects S3 requests from compactor, store-gateway and querier.

### Shuffle sharding
One potential solution is to use shuffle sharding and limit the number of ingesters to which one tenant’s time series is distributed. This also has the added benefit of reducing the blast radius of one tenant behaving badly. See: https://aws.amazon.com/blogs/architecture/shuffle-sharding-massive-and-magical-fault-isolation/

**Comment by pracucci** [comment]
👋  Hello! Thanks for opening this issue.

The issue you describe is real and it's something we're brainstorming on since some time. As an experiment, we've introduced the "subring" which is a basic version of the shuffle sharding.

The subring can be enabled via the CLI flag `-experimental.distributor.user-subring-size` (there's also a config file enytry) and it's the number of ingesters across which each tenant's series should be sharded/replicated. If you set a subring size=5 it means each tenant series will be distributed across 5 ingesters and not all ingesters.

The subring is currently an experiment and I'm not aware of anyone running it in production, but I'm very open to discuss to improve it further. The first limitations that come to my mind are:
1. The subring size is fixed (can't be customized per tenant, can't be automatically adjusted per tenant based on the active series)
2. The queriers still need to fetch series from all ingesters because they don't know which ingesters are holding series for a tenant. It's not safe to just look at the current state of the ring  because a resharding could occur anytime (ie. during ingesters rollout or scale up/down). An option could be propagating to the queriers the information about the list of tenants for which each ingester holds at least 1 series, so that queriers know which ingesters should be queried for each tenant's query.

We would need some help from people experienced on the shuffle sharding to better learn techniques to address these (and possibly other) limitations.

**Comment by harry671003** [comment]
Based on our tests, the ingester subring did reduce the requests to S3 by a lot. But metadata sync from queriers and store-gateway still doesn't scale well in large clusters. 

- Will the new TSDB metadata cache address this issue? 
- Or should shuffle sharding be implemented in these components as well? I saw this [issue](https://github.com/cortexproject/cortex/issues/961) that mentions shuffle-sharding in queriers.

**Comment by pracucci** [comment]
> Will the new TSDB metadata cache address this issue?

Yes. We're running it with the metadata cache and improve things a lot. We've also introduced jitters to the querier and store-gateway scan frequency to help cacheabilty. Could give it a try and let me know, please?

**Comment by harry671003** [comment]
> The subring can be enabled via the CLI flag -experimental.distributor.user-subring-size (there's also a config file enytry) and it's the number of ingesters across which each tenant's series should be sharded/replicated. If you set a subring size=5 it means each tenant series will be distributed across 5 ingesters and not all ingesters.

I noticed an issue with time-series allocation after enabling `-experimental.distributor.user-subring-size = 3` and `-distributor.replication-factor=3`.  In a cluster with 12 ingesters and 13 tenants, only 5 ingesters store any time-series. The remaining 7 ingesters have 0 active time-series.

![Screen Shot 2020-06-30 at 2 30 46 PM](https://user-images.githubusercontent.com/842522/86179317-dfe42b80-bade-11ea-84ed-f023112dbb5c.png)  [Graphana Snapshot](https://snapshot.raintank.io/dashboard/snapshot/8GdqMjFbcB9GC39Krr8Pguv95FFmcuqZ?orgId=2)

Why weren't time-series distributed more evenly across all ingesters. Could this be a bug or something to be expected after enabling this flag?


> Yes. We're running it with the metadata cache and improve things a lot. We've also introduced jitters to the querier and store-gateway scan frequency to help cacheabilty. Could give it a try and let me know, please?

This did work. Total S3 GET requests are way less than before.

**Comment by pracucci** [comment]
> I noticed an issue with time-series allocation after enabling -experimental.distributor.user-subring-size = 3 and -distributor.replication-factor=3. In a cluster with 12 ingesters and 13 tenants, only 5 ingesters store any time-series. The remaining 7 ingesters have 0 active time-series.

It's unexpected and could be a bug, unless the 13 tenant names are so unlucky to have their hash falling into the same shard. Have you tried increasing the number of ring tokens per ingester? The `-ingester.num-tokens` default is `128` but in our clusters we use `512` to have a better spread.

**Comment by thorfour** [comment]
> The subring size is fixed (can't be customized per tenant, can't be automatically adjusted per tenant based on the active series)

SubringSize is apart of the Limits struct and can actually be customized per tenant. Though you are correct in that it doesn't dynamically size itself.

**Comment by harry671003** [comment]
> Have you tried increasing the number of ring tokens per ingester?

Yes, I tried again with 512 tokens, but saw similar issues in time-series distribution.


> It's unexpected and could be a bug, unless the 13 tenant names are so unlucky to have their hash falling into the same shard.

I tried to compute the hash values of each tenant in our cluster: "tenant-1", "tenant-2", .. , "tenant-13". 

```
for i := 1; i <= 13; i++ {
    tenant := "tenant-" + strconv.Itoa(i);
    h := HashAdd32(HashNew32(), tenant);
    fmt.Printf("hash(%v)= %v \n", tenant, h);
}

OUTPUT
---------
h('tenant-1')= 1590364151 
h('tenant-2')= 1590364148 
h('tenant-3')= 1590364149 
h('tenant-4')= 1590364146 
h('tenant-5')= 1590364147 
h('tenant-6')= 1590364144 
h('tenant-7')= 1590364145 
h('tenant-8')= 1590364158 
h('tenant-9')= 1590364159 
h('tenant-10')= 815630821 
h('tenant-11')= 815630820 
h('tenant-12')= 815630823 
h('tenant-13')= 815630822
```

These values looks very close. I believe this is likely the problem.

**Comment by harry671003** [comment]
There seems to be a bug in the implementation of fnv32a function. I believe https://github.com/cortexproject/cortex/blob/master/pkg/ingester/client/fnv.go#L66 should instead be 
```go
func HashAdd32(h uint32, s string) uint32 {
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i]) // first XOR
		h *= prime32 // then multiply by prime32
	}
	return h
}
```

And after making this change,

```go

for i := 1; i <= 13; i++ {
    tenant := "tenant-" + strconv.Itoa(i);
    h := HashAdd32(HashNew32(), tenant);
    fmt.Printf("hash(%v)= %v \n", tenant, h);
}

/*
OUTPUT
------

h('tenant-1')= 1127395211 
h('tenant-2')= 1144172830 
h('tenant-3')= 1160950449 
h('tenant-4')= 1177728068 
h('tenant-5')= 1194505687 
h('tenant-6')= 1211283306 
h('tenant-7')= 1228060925 
h('tenant-8')= 976396640 
h('tenant-9')= 993174259 
h('tenant-10')= 2211095393 
h('tenant-11')= 2194317774 
h('tenant-12')= 2177540155 
h('tenant-13')= 2160762536 
*/
```

**Comment by harry671003** [comment]
Saw this [PR](https://github.com/cortexproject/cortex/pull/1343) which reverted the hash function from FNV-1a back to FNV-1.

However, I believe FNV-1a should be used for SubRing instead of FNV-1 for better distribution.

@thorfour, @pracucci What do you guys think?

**Comment by pstibrany** [comment]
> Saw this [PR](https://github.com/cortexproject/cortex/pull/1343) which reverted the hash function from FNV-1a back to FNV-1.

We don't want to change hashing function for series -> token, because each such change causes massive disruption to large clusters. (Even though it would give a better distribution, but in case of series, we also take labels into account, so the problem is not so bad)

However, for subring and tenants, I think using hash function with better distribution makes sense. Tenant ids are shorter, and subring is experimental feature still, with very few installations.

**Comment by pracucci** [comment]
> However, for subring and tenants, I think using hash function with better distribution makes sense. Tenant IDs are much shorter with less randomness in them, and subring is experimental feature still, with very few installations.

@harry671003 Thanks for spotting the issue! I 💯  with Peter on this. It's a bug we should fix for the tenants hashing in the subring only. Harry, would you be open to submit a PR to fix it, please?

**Comment by harry671003** [comment]
Sure, I'm happy to help. Thanks for confirming that this is indeed an issue. I will raise a PR within the next few days.
