### ISSUE TITLE
Query block storage store for data longer than 1h return error

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#3497]
**Describe the bug**
Not sure what I am doing wrong here - Scenario description
I have multiple Prom servers sending data to a Cortex environment in GCP running on GKE.  I deployed Cortex with Block storage engine using GCS
My write path seemed to be OK as I can see chunks are written out to GCS and the ingestors and compactors show no errors
My Read path however seemed to have multiple issues.  Using grafana  I can only see data for the last hour.  Any query period more than 1 hr return no data with the following error on grafana and query-frontend

```
"expanding series: failed to fetch series from store-gateway.monitoring.svc.cluster.local:80: rpc error: code = Unavailable desc = connection closed"
```
The following seem to affect this behavior somewhat for the querier
```
       - -querier.ingester-streaming=false
        - -querier.query-ingesters-within=3h
        - -querier.query-store-after=90m
        - -querier.store-gateway-addresses=store-gateway.monitoring.svc.cluster.local:80
```

The ingester configuration related to data retention and written to the back end is as followed
```
           - -ingester.wal-dir=/tmp/ingester
            - -ingester.checkpoint-duration=15m
            - -ingester.recover-from-wal=true
            - -ingester.tokens-file-path=/tmp/ingester
            - -ingester.max-chunk-age=1h
           - -blocks-storage.tsdb.block-ranges-period=1h0m0s
            - -blocks-storage.tsdb.retention-period=3h0m0s   
```

Any suggestion is greatly appreciated.  I am stumped on this for a couple of days now
**Additional Context**

**Comment by pracucci** [comment]
> "expanding series: failed to fetch series from store-gateway.monitoring.svc.cluster.local:80: rpc error: code = Unavailable desc = connection closed"

The store-gateway endpoint should be the gRPC endpoint, not the HTTP one. The port 80 is the HTTP port, while the gRPC (default) port is `9095`.

**Comment by mizunos** [comment]
Thanks for getting back to me 
I made the change to point to gRPC port for storage-gateway and now I do not even get anything on Grafana for any time frame - The error on Grafana show `too many outstanding request` when I try to change the time frame

The query-frontend log show the following error
```
level=error ts=2020-11-17T20:33:01.319662933Z caller=retry.go:71 msg="error processing request" try=0 err="context canceled"                                                                         │
│ level=debug ts=2020-11-17T20:33:01.320637982Z caller=logging.go:66 traceID=7269c4632faa5b6f msg="POST /api/prom/api/v1/query_range (499) 29.989377559s"                                              │
│ level=debug ts=2020-11-17T20:33:04.648747233Z caller=logging.go:66 traceID=4babb01ddabe10f0 msg="GET /metrics (200) 5.046689ms"                                                                      │
│ level=error ts=2020-11-17T20:33:15.33897415Z caller=retry.go:71 msg="error processing request" try=0 err="context canceled"                                                                          │
│ level=debug ts=2020-11-17T20:33:15.339189882Z caller=logging.go:66 traceID=2ce7fb249a4a6c42 msg="POST /api/prom/api/v1/query_range (499) 29.994524063s"
```
The Read path is configured as followed:

query-frontend
```
       args:
        - -target=query-frontend
        - -log.level=debug
        - -server.http-listen-port=80
        - -server.grpc-listen-port=9095
        - -store.engine=blocks
        - -querier.cache-results=false
        - -querier.store-gateway-addresses=store-gateway.monitoring.svc.cluster.local:9095
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=edge-monitor-block-storage
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
       ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 80
          name: http
```

querier
```
        args:
        - -target=querier
        - -server.http-listen-port=80
        - -server.grpc-listen-port=9095
        - -store.engine=blocks
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -querier.frontend-address=dnssrvnoa+_query-frontend._tcp.query-frontend.monitoring.svc.cluster.local:9095
        - -querier.ingester-streaming=false
        - -querier.query-ingesters-within=2h
        - -querier.query-store-after=90m
        - -querier.store-gateway-addresses=store-gateway.monitoring.svc.cluster.local:9095
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=edge-monitor-block-storage
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
       ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 80
```

store-gateway
```
      args:
        - -target=store-gateway
        - -store.engine=blocks
        - -store-gateway.sharding-enabled=false
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=edge-monitor-block-storage
        - -blocks-storage.bucket-store.sync-interval=2m
        - -blocks-storage.bucket-store.max-concurrent=100
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+_memcached._tcp.memcached.monitoring.svc.cluster.local:11211
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 80
          name: http
```

I am kind of really stuck so really appreciate any pointers here.

**Comment by pstibrany** [comment]
> -querier.frontend-address=dnssrvnoa+_query-frontend._tcp.query-frontend.monitoring.svc.cluster.local:9095

Frontend address can only be specified in `host:port`. [DNS Service Discovery](https://cortexmetrics.io/docs/configuration/arguments/#dns-service-discovery) is not yet supported for this parameter.

**Comment by wangzhao765** [comment]
-querier.query-ingesters-within=3h
-ingester.max-chunk-age=1h

It seems that your ingester can keep 1h data. But your querier will send queries within 3h to ingester. So I guess that when the range is longer than 1h, querier cannot get data from ingester. Is that the reason?

**Comment by pracucci** [comment]
> -querier.query-ingesters-within=3h
> -ingester.max-chunk-age=1h
> 
> It seems that your ingester can keep 1h data. But your querier will send queries within 3h to ingester. So I guess that when the range is longer than 1h, querier cannot get data from ingester. Is that the reason?

A couple of notes:
- `-ingester.max-chunk-age=1h` applies only to the chunks storage (not the blocks storage)
- It's not a problem if `-querier.query-ingesters-within=3h` is greater than the retention period in the ingesters

I think the problem described in this GitHub issue was caused by a misconfigured store-gateway and query-frontend address (Peter comment should address it).

_I'm going to close this issue, but feel free to comment / re-open if wasn't addressed in previous comments._

**Comment by Rahuly360** [comment]
@mizunos : I am still getting this issue. Did you find any solution for the same?
